name: Deploy BOFH to Prod

concurrency: 
  group: environment-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - '**.js'
      - 'serverless.yml'
      - 'excuses.txt'
      - 'yarn.lock'
      - 'package.json'
      - '.github/workflows/*-prod.yml'

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

jobs:
  bc:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v3.3.0
        - name: Run Bridgecrew 
          id: Bridgecrew
          uses: bridgecrewio/bridgecrew-action@master 
          with:
            api-key: ${{ secrets.BC_API_KEY }}

  deploy-prod:
    runs-on: ubuntu-latest
    needs: bc
    environment: production
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: actions/setup-node@v3.6.0
      with:
        node-version: '18.x'
    - name: Install Serverless Framework
      run: yarn global add serverless
    - name: Serverless AWS authentication
      run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile default
    - name: Install NPM dependencies
      run: yarn install
    - name: Deploy Lambda functions
      run: sls deploy -s prod
    - name: Update Cloudflare DNS Record
      run: sls cloudflare record update
