name: Deploy BOFH to Prod
on:
  push:
    branches:
      - main
jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install Serverless Framework
      run: yarn add -g serverless
    - name: Serverless AWS authentication
      run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile default
    - name: Install NPM dependencies
      run: yarn install
    - name: Deploy Lambda functions
      run: sls deploy -s prod